#!/usr/bin/env ruby
require File.join('lib', 'framework')

begin
  require 'waves'
  Waves::Console.load(:mode => ENV['mode'])
  %w( schema cluster generate gem ).each { |task| require "lib/tasks/#{task}.rb" }
rescue LoadError
  puts "Can't find waves gem or ./waves/lib directory.  try rake symlink waves=/path/to/waves/"
end

desc "Create lib and bin symlinks using waves=<path>"
task :symlink do
  waves = ENV['waves']
  system "mkdir waves"
  libdir = File.join(waves, 'lib')
  bindir = File.join(waves, 'bin')
  system(cmd = "ln -s #{libdir} waves/") && puts(cmd)
  system(cmd = "ln -s #{bindir} waves/") && puts(cmd)
end