#!/usr/bin/env ruby
require File.join('lib', 'framework')

begin
  require 'waves'
  Waves::Console.load(:mode => ENV['mode'])
  %w( schema cluster generate gem ).each { |task| require "lib/tasks/#{task}.rb" }
rescue LoadError
  puts "Can't find waves.  Install the gem or define WAVES_SRC in lib/framework.rb"
end

desc "Deprecated. Create lib and bin symlinks using waves=<path>"
task :symlink do
  puts "You need to define WAVES_SRC in lib/framework.rb for this to work"
  waves = ENV['waves']
  system "mkdir waves"
  libdir = File.join(waves, 'lib')
  bindir = File.join(waves, 'bin')
  system(cmd = "ln -s #{libdir} waves/") && puts(cmd)
  system(cmd = "ln -s #{bindir} waves/") && puts(cmd)
end