#!/usr/bin/env ruby
USE_WAVES_SRC = true
$: << File.expand_path('../../lib')
require File.join(File.expand_path('../..'), 'lib', 'waves')
Waves::Console.load(:mode => ENV['mode'])
%w( schema cluster generate ).each { |task| require "lib/tasks/#{task}.rb" }

task :specrb do
  specs = Dir[ :verify / :spec / '*.rb' ]
  `specrb -r../helpers #{specs.join(' ')} --rdox > doc/SPEC`
end

task :verify => [:'cluster:start', :specrb, :'cluster:stop'] do
end